### ISSUE TITLE
Container Scenarios - update example/docs to list all usable keys

### ISSUE THREAD

**Issue by lugi0** [redhat-chaos/krkn#414]
In the current main branch of the repo, the keys that can be used when defining a container scenario are split among the example file (`scenarios/container_etcd.yml`) and documentation file (`docs/container_scenarios.md`).
`container_etcd.yml`
```
scenarios:
- name: "kill etcd container"
  namespace: "openshift-etcd"
  label_selector: "k8s-app=etcd"
  container_name: "etcd"
  action: "kill 1"
  count: 1
  retry_wait: 60
```
`container_scenarios.md`
```
scenarios:
- name: "<Name of scenario>"
  namespace: "<specific namespace>" # can specify "*" if you want to find in all namespaces
  label_selector: "<label of pod(s)>"
  container_name: "<specific container name>"  # This is optional, can take out and will kill all containers in all pods found under namespace and label
  pod_names:  # This is optional, can take out and will select all pods with given namespace and label
  - <pod_name>
  retry_wait: <number of seconds to wait for container to be running again> (defaults to 120seconds)
```

I think both files should be updated to include all keys in both locations, to make it clearer that every key shown in the repo is currently supported. 
I would also add a comment specifying what `action` and `count` are exactly controlling in the scenario, since those are the only two keys without any documentation.
